version: 2
jobs:
  build:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Show versions
          command: swift --version
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test
